[package]
name = "fixed-macro"
version = "0.1.0"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
edition = "2018"

[workspace]
members = [".", "fixed-macro-impl"]
default-members = [".", "fixed-macro-impl"]

[dependencies]
fixed-macro-impl = { version = "0.1.0", path = "fixed-macro-impl" }
