[package]
name = "fixed-macro-types"
version = "0.1.0"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
edition = "2018"

[dependencies]
fixed = "1"
fixed-macro-impl = { version = "0.1.0", path = "../fixed-macro-impl" }
